// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

<<<<<<< HEAD
import ImagePreviewController from "./image_preview_controller"
application.register("image-preview", ImagePreviewController)
=======
import HelloController from "./hello_controller"
application.register("hello", HelloController)
>>>>>>> 81dd2749b47c942904553ec36883c554e458af9b
