test:
    adapter: mysql2
    encoding: utf8mb4
    database: aw0tba0hfjyqyf21
    username: mof3sm8nhO7BN5KE
    password: P512B8WU39B35Y1T
    host: d13xat1hwxt21t45.cbetxkdyhwsb.us-east-1.rds.amazonaws.com	
