// Entry point for the build script in your package.json
import "@hotwired/turbo-rails"
import "./controllers"
import * as bootstrap from "bootstrap"
import "chartkick/chart.js"
import "./intersection_observer"
import "./dark_mode"
import "./preview"
import "./quantity_change"
import "./whiskey_star"
import "./cocktail_star"
import "./cocktail_animation"
import "./whiskey_animation"
import "./select_whiskey"
import "./scroll"
