// Entry point for the build script in your package.json
import "./intersection_observer"
import "./dark_mode"
import "./loading"
import "./preview"
import "./quantity_change"
import "./whiskey_star"
import "./cocktail_star"
import "./distillery"
import "@hotwired/turbo-rails"
import "./controllers"
import * as bootstrap from "bootstrap"
import "chartkick/chart.js"
